services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8022:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
      - DOCS_ENDPOINT=http://localhost:3000/api/documentos
      - SENTENCE_TRANSFORMER=all-MiniLM-L6-v2
    restart: always